# This is a basic workflow to help you get started with Actions

name: Build Gradle

# Controls when the workflow will run
on:
  pull_request: # Triggers the workflow on push or pull request events
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-jobs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run'))
    steps:
      - uses: actions/checkout@v4

      - name: Adjust Branch
        if: github.event_name == 'issue_comment'
        run: |
          gh pr checkout ${{ github.event.issue.number }}
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/issues/${{ github.event.issue.number }}/comments \
            -f body='Me too' 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: TESTS
        run: |
          echo ${{ steps.get-branch.outputs.branch }}
          echo ${{ steps.refs.outputs.base_ref }}
          ls
          cat test.txt
     
