# This is a basic workflow to help you get started with Actions

name: Build Gradle

# Controls when the workflow will run
on:
  pull_request: # Triggers the workflow on push or pull request events
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-jobs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run'))
    steps:
      - uses: actions/checkout@v4

      - name: Adjust Branch
        if: github.event_name == 'issue_comment'
        run: |
          gh pr checkout ${{ github.event.issue.number }}
          RUNID=$(gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA/check-runs | jq -r '.check_runs[] | select(.name == "NAME_OF_YOUR_GITHUB_ACTIONS_WORKFLOW") | .html_url | capture("/runs/(?<number>[0-9]+)/job") | .number' | sed 's/"//g' | head -n 1)
          echo RUNID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: TESTS
        run: |
          echo ${{ steps.get-branch.outputs.branch }}
          echo ${{ steps.refs.outputs.base_ref }}
          ls
          cat test.txt
     
