# This is a basic workflow to help you get started with Actions

name: Build Gradle

# Controls when the workflow will run
on:
  pull_request: # Triggers the workflow on push or pull request events
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-jobs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run'))
    steps:
      - name: Github API Request
        id: request
        if: github.event_name == 'issue_comment'
        uses: octokit/request-action@v2.0.0
        with:
          route: ${{ github.event.issue.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: Checkout PR Branch
        if: github.event_name == 'issue_comment'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
          ref: ${{ steps.pr_data.outputs.branch }}

        
