# This is a basic workflow to help you get started with Actions

name: Build Gradle

# Controls when the workflow will run
on:
  pull_request: # Triggers the workflow on push or pull request events
  issue_comment:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  print-jobs:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run'))
    steps:
      - name: Checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - name: Adjust Checkout
        if: github.event_name == 'issue_comment'
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head


      - name: rerun
        if: github.event_name == 'issue_comment'
        run: gh run rerun 8468124148
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
