name: re-run workflow

# Controls when the workflow will run
on:
  issue_comment:
    type: [created]

jobs:
  rerun-workfow:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run')
    steps:
      - id: 'get-branch'
        # run: echo ::set-output name=branch::$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')
        run: echo "branch=$(gh pr view $PR_NO --repo $REPO --json headRefName --jq '.headRefName')" >> "$GITHUB_OUTPUT"
        # run: echo "{name}={value}" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
          PR_NO: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ steps.get-branch.outputs.branch }}
          # ${{ steps.comment-branch.outputs.head_ref }}

      - name: Rerun Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}/dispatches \
            -d '{"ref":"${{ steps.get-branch.outputs.branch }}"}'
      
      #- run: |
      #    git commit -m "${{ steps.get-branch.outputs.branch }} retrigger checks" --allow-empty
      #    git push
      # gh workflow run test.yml -r ${{ steps.get-branch.outputs.branch }}
      #  env:
      #    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
