name: re-run workflow

# Controls when the workflow will run
on:
  issue_comment:
    type: [created]

jobs:
  rerun-workfow:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run')
    steps:
      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - uses: actions/github-script@v7.0.1
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
        
      - uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}
          # ${{ steps.comment-branch.outputs.head_ref }}
      
      - run: gh workflow run test.yml -r refs/pull/${{ github.event.issue.number }}/head
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
