# This is a basic workflow to help you get started with Actions

name: Build Gradle

# Controls when the workflow will run
on:
  pull_request: # Triggers the workflow on push or pull request events
  issue_comment:
    type: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pr-commented:
    name: PR commented
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/run'))
    steps:
      # Checkout source code
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout Pull Request Issue Comments
        if: github.event_name == 'issue_comment'
        run: hub pr checkout ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: resolve pr refs
        id: refs
        uses: eficode/resolve-pr-refs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: TESTS
        run: |
          echo ${{ steps.get-branch.outputs.branch }}
          ls
          cat test.txt
    
     
