# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request: # Triggers the workflow on push or pull request events
  issue_comment:
    type: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build: # This workflow contains a single job called "build"
    # The type of runner that the job will run on
    if: github.event_name == 'pull_request' || (contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'run workflow'))
    runs-on: ubuntu-latest
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - name: Fetch Pull Request Info
        if: github.event.issue.pull_request
        run: |
          pull_request_url=$(jq -r '.issue.pull_request.url' "$GITHUB_EVENT_PATH")
          branch=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$pull_request_url" | jq -r '.head.ref')
          echo "Branch Name: $branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Runs a single command using the runners shell
      - name: output file
        run: cat test.txt

      - name: Print sha and ref
        run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REF

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
