# This is a basic workflow to help you get started with Actions

name: Build Gradle

# Controls when the workflow will run
on:
  workflow_dispatch:
  pull_request: # Triggers the workflow on push or pull request events

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pr-commented:
    name: PR commented
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: TESTS
        run: |
          echo ${{ steps.get-branch.outputs.branch }}
          echo ${{ steps.refs.outputs.base_ref }}
          ls
          cat test.txt
     
